# Generated by Django 3.2 on 2021-05-02 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['-movie_title'],
            },
        ),
        migrations.CreateModel(
            name='MovieRatings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratings_descriptions', models.TextField()),
                ('published', models.DateField(auto_now=True)),
                ('movie_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_list', to='api.movielist')),
            ],
            options={
                'ordering': ['-ratings_descriptions'],
            },
        ),
    ]
