# Generated by Django 3.2 on 2021-05-04 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_movieratings_ratings_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielist',
            name='movie_title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
